version: "2"
plugins:
  duplication:
    enabled: false
  rubocop:
    channel: rubocop-0-52
    enabled: true
    config:
      file: .rubocop.yml
ratings:
  paths:
  - "spec/tests/**.rb"
  - "lib/**.rb"
